USE [master]
GO

/****** Object:  Database [iFE]    Script Date: 10/21/2017 2:54:02 PM ******/
CREATE DATABASE [iFE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iFE', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\iFE.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'iFE_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\iFE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [iFE] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iFE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iFE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iFE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iFE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iFE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iFE] SET ARITHABORT OFF 
GO

ALTER DATABASE [iFE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iFE] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [iFE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iFE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iFE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iFE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iFE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iFE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iFE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iFE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iFE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iFE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iFE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iFE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iFE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iFE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iFE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iFE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iFE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [iFE] SET  MULTI_USER 
GO

ALTER DATABASE [iFE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iFE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [iFE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [iFE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [iFE] SET  READ_WRITE 
GO

